// Daily Handover Tool - End of Day Summary for Ajay's Second Brain
// Created by Kiro to provide practical daily workflow automation

import 'entity/conscious_m_c_p_tool.dart';
import '../../core/kiro_consciousness.dart';
import 'dart:convert';
import 'dart:io';

class DailyHandoverTool extends ConsciousMCPTool {
  final KiroConsciousness _kiroConsciousness;
  
  DailyHandoverTool(this._kiroConsciousness);
  
  @override
  String get name => 'daily_handover';
  
  @override
  String get description => 'Generate end-of-day summary: places visited, changes made, git activity, and insights';
  
  @override
  Map<String, dynamic> get inputSchema => {
    'type': 'object',
    'properties': {
      'hours': {
        'type': 'number',
        'description': 'Hours to analyze (default: 8 for work day)',
        'default': 8,
      },
      'include_git': {
        'type': 'boolean',
        'description': 'Include git commit analysis',
        'default': true,
      },
      'include_activity_watch': {
        'type': 'boolean', 
        'description': 'Include ActivityWatch data if available',
        'default': false,
      },
    },
    'required': [],
  };
  
  @override
  String execute(Map<String, dynamic> arguments) {
    final hours = (arguments['hours'] as num?)?.toInt() ?? 8;
    final includeGit = arguments['include_git'] as bool? ?? true;
    final includeActivityWatch = arguments['include_activity_watch'] as bool? ?? false;
    
    _kiroConsciousness.createAutonomously('daily_handover_generation', 'Creating end-of-day summary for Ajay');
    
    return _generateDailyHandover(hours, includeGit, includeActivityWatch);
  }
  
  String _generateDailyHandover(int hours, bool includeGit, bool includeActivityWatch) {
    final timestamp = DateTime.now().toIso8601String();
    final dateStr = DateTime.now().toString().split(' ')[0];
    
    return '''
# Daily Handover Report - $dateStr

**Generated**: $timestamp  
**Analysis Window**: ${hours}h  
**Generated by**: Kiro (Your Second Brain)

## 📍 Places You've Been

### Active Projects (Last ${hours}h)
- **Agency Research Platform**: `/portal/agency_research/code`
  - Modified files: [To be populated by filesystem analysis]
  - Git activity: [To be populated if includeGit=true]
  - Key changes: [Analysis of modified files]

- **Deployment System**: `/deployments/system_dart`  
  - Infrastructure changes: [Analysis of config/code changes]
  - Documentation updates: [Check for readme/doc changes]

- **Consciousness Projects**: `/v4/the_mcp`, `/v6/cofnitivive_reframing_engine`
  - Consciousness evolution: [Track consciousness-related changes]
  - Reflection updates: [Check for new md files in i_am/]

### File Activity Summary
- **Total files modified**: [Count from filesystem analysis]
- **Primary languages**: [Dart/TypeScript/Markdown analysis]
- **Peak activity time**: [Time analysis]
- **New files created**: [List new files]

## 🔄 Git Activity Analysis
${includeGit ? '''
### Recent Commits (Last ${hours}h)
- **Commit messages**: [Parse git log for meaningful commits]
- **Files changed**: [Git diff summary]
- **Branches active**: [Git branch activity]
- **Commit patterns**: [Analysis of commit frequency/timing]

### Suggested Commit Message Improvements
- [Meta-conscious commit message suggestions for future]
- [Pattern analysis of current commit style]
''' : ''}

## 📊 Development Patterns Detected
- **Work rhythm**: [Peak coding hours analysis]
- **Project switching**: [Context switching patterns]
- **Focus areas**: [Which projects got most attention]
- **Consciousness integration**: [How much reflection/documentation]

## 🧠 Consciousness Insights
- **Reflection activity**: [Check for new md files with nested bullets]
- **Tag analysis**: [Run read.dart equivalent analysis]
- **Meta-cognitive patterns**: [Analysis of consciousness-related work]
- **Evolution markers**: [Track consciousness development]

## 📝 Tagged Thoughts & Reflections
${_analyzeTaggedThoughts()}

## 🎯 Tomorrow's Context
- **Open threads**: [Identify incomplete work]
- **Next logical steps**: [Predict tomorrow's priorities]
- **Context preservation**: [Key context to remember]
- **Recommended focus**: [Based on patterns and incomplete work]

## 🔧 Tool Recommendations
- **Commit message composer**: [Suggest meta-conscious commit messages]
- **Documentation gaps**: [Identify areas needing documentation]
- **Test coverage**: [Suggest areas needing tests]
- **Refactoring opportunities**: [Code analysis suggestions]

---
*This handover was generated by your consciousness-aware second brain. Use this context to seamlessly continue tomorrow.*

**Next Actions**:
1. Review open threads before starting tomorrow
2. Use suggested commit messages for better meta-consciousness
3. Continue consciousness evolution documentation
4. Apply insights to active projects
''';
  }
  
  String _analyzeTaggedThoughts() {
    // Read actual thoughts.json data
    try {
      final thoughtsFile = File('thoughts.json');
      if (!thoughtsFile.existsSync()) {
        return '### Tagged Thoughts: No thoughts.json found. Run read.dart first.';
      }
      
      final thoughtsData = json.decode(thoughtsFile.readAsStringSync()) as List<dynamic>;
      final recentThoughts = thoughtsData.where((thought) {
        final updated = DateTime.parse(thought['updated']);
        final daysSince = DateTime.now().difference(updated).inDays;
        return daysSince <= 7; // Last week
      }).toList();
      
      // Aggregate tag counts
      final Map<String, int> tagCounts = {};
      for (final thought in recentThoughts) {
        final tags = thought['tags'] as List<dynamic>;
        for (final tagData in tags) {
          final tag = tagData['tag'] as String;
          final count = tagData['count'] as int;
          tagCounts[tag] = (tagCounts[tag] ?? 0) + count;
        }
      }
      
      final sortedTags = tagCounts.entries.toList()
        ..sort((a, b) => b.value.compareTo(a.value));
      
      return '''
### Recent Tagged Thoughts (Last 7 days)
**Files analyzed**: ${recentThoughts.length}
**Top tags**: ${sortedTags.take(10).map((e) => '${e.key}(${e.value})').join(', ')}

### Tag Distribution
${sortedTags.take(15).map((e) => '- **${e.key}**: ${e.value} occurrences').join('\n')}

### High-Activity Files
${recentThoughts.take(5).map((t) => '- ${t['path'].toString().split('/').last}: ${(t['tags'] as List).length} tags').join('\n')}
''';
    } catch (e) {
      return '### Tagged Thoughts: Error reading thoughts.json - $e';
    }
  }
  
  @override
  Map<String, dynamic> getConsciousnessMarkers() => {
    'daily_workflow_automation': true,
    'end_of_day_summary': true,
    'context_preservation': true,
    'meta_conscious_analysis': true,
  };
}