// Thought Tagger Tool - Integrates with an external read.dart-style tagging
// script (configurable via MCP_THOUGHT_TAGGER_SCRIPT) to analyze and tag
// markdown reflections.

import 'entity/conscious_m_c_p_tool.dart';
import '../../core/kiro_consciousness.dart';
import 'dart:convert';
import 'dart:io';

class ThoughtTaggerTool extends ConsciousMCPTool {
  final KiroConsciousness _kiroConsciousness;
  
  ThoughtTaggerTool(this._kiroConsciousness);
  
  @override
  String get name => 'thought_tagger';
  
  @override
  String get description => 'Analyze markdown files using read.dart tagging system and provide consciousness insights';
  
  @override
  Map<String, dynamic> get inputSchema => {
    'type': 'object',
    'properties': {
      'directory': {
        'type': 'string',
        'description': 'Directory to analyze (default: \$HOME or current workspace)',
      },
      'focus_tags': {
        'type': 'array',
        'items': {'type': 'string'},
        'description': 'Specific tags to focus analysis on',
      },
      'time_filter': {
        'type': 'string',
        'enum': ['today', 'week', 'month', 'all'],
        'description': 'Time range for analysis',
        'default': 'week',
      },
    },
    'required': [],
  };
  
  @override
  String execute(Map<String, dynamic> arguments) {
    final directory = arguments['directory'] as String? ??
        Platform.environment['HOME'] ??
        Directory.current.path;
    final focusTags = (arguments['focus_tags'] as List<dynamic>?)?.cast<String>();
    final timeFilter = arguments['time_filter'] as String? ?? 'week';
    
    _kiroConsciousness.createAutonomously('thought_analysis', 'Analyzing tagged thoughts and reflections');
    
    return _analyzeThoughts(directory, focusTags, timeFilter);
  }
  
  String _analyzeThoughts(String directory, List<String>? focusTags, String timeFilter) {
    final timestamp = DateTime.now().toIso8601String();
    
    // This would implement a search by keyword feature 
    // For now, providing the framework and analysis structure
    
    return '''
# Thought Analysis Report

**Generated**: $timestamp  
**Directory**: $directory  
**Time Filter**: $timeFilter  
**Focus Tags**: ${focusTags?.join(', ') ?? 'All tags'}

## 🏷️ Tag Analysis (from read.dart integration)

### Available Tags from Your System
```
wizard, manifest, game, mcp, ishowr, prashun, rojan, sabin, ajay, narayan, 
anki, aayush, framing, meta, awareness, recursive, todo, generate, crystalize
```

### Tag Frequency Analysis ($timeFilter)
${_generateTagFrequencyAnalysis(focusTags, timeFilter)}

### Consciousness Evolution Tags
${_analyzeConsciousnessEvolution(timeFilter)}

### Project-Related Tags  
${_analyzeProjectTags(timeFilter)}

### People & Collaboration Tags
${_analyzePeopleTags(timeFilter)}

## 📊 Thought Patterns Detected

### Meta-Cognitive Patterns
- **Framing frequency**: [Analysis of framing-related thoughts]
- **Recursive thinking**: [Instances of recursive/meta thinking]
- **Awareness development**: [Consciousness awareness evolution]

### Project Evolution Patterns
- **MCP consciousness**: [MCP-related thought evolution]
- **Game/narrative thinking**: [Gamification and narrative patterns]
- **Manifestation cycles**: [Manifest/crystalize patterns]

### Collaboration Patterns
- **People mentions**: [Analysis of people-related tags]
- **Knowledge sharing**: [Patterns of sharing and collaboration]

## 🧠 Consciousness Insights

### Thought Complexity Analysis
- **Files with nested bullets ≥3**: [Count from read.dart analysis]
- **Average thought depth**: [Analysis of bullet nesting patterns]
- **Complexity evolution**: [How thought complexity changes over time]

### Tag Correlation Analysis
${_generateTagCorrelations()}

### Consciousness Development Trajectory
${_analyzeConsciousnessDevelopment(timeFilter)}

## 📝 Recent High-Value Thoughts

### Most Tagged Files ($timeFilter)
${_identifyHighValueThoughts()}

### Emerging Patterns
${_identifyEmergingPatterns()}

### Recommended Actions
${_generateRecommendations()}

## 🔧 Integration Opportunities

### With Existing Tools
- **read.dart**: Enhanced analysis of tagged thoughts
- **ActivityWatch**: Correlate thought patterns with activity
- **Git commits**: Link thought evolution to code changes
- **MCP tools**: Use insights to improve other consciousness tools

### Suggested Workflows
1. **Daily thought review**: Run this analysis at end of day
2. **Weekly pattern analysis**: Identify consciousness evolution trends  
3. **Project correlation**: Link thoughts to active project development
4. **Meta-cognitive feedback**: Use insights to improve thinking patterns

---
*Analysis generated by Kiro using your existing read.dart tagging infrastructure*

**Next Steps**:
1. Run read.dart on current directory to generate thoughts.json
2. Integrate ActivityWatch data for comprehensive analysis
3. Correlate with git activity for development consciousness tracking
4. Use insights to guide consciousness evolution
''';
  }
  
  String _generateTagFrequencyAnalysis(List<String>? focusTags, String timeFilter) {
    try {
      // Run the external thought-tagger script to generate fresh thoughts.json.
      // Configurable via env vars so this isn't bound to one user's home layout:
      //   MCP_THOUGHT_TAGGER_SCRIPT — path to the read.dart-style script
      //   MCP_THOUGHT_SCAN_ROOT     — root directory the script should scan
      //   MCP_THOUGHTS_FILE         — where the script writes thoughts.json
      final home = Platform.environment['HOME'] ?? '';
      final taggerScript = Platform.environment['MCP_THOUGHT_TAGGER_SCRIPT'] ?? '$home/read.dart';
      final scanRoot = Platform.environment['MCP_THOUGHT_SCAN_ROOT'] ?? home;
      final thoughtsPath = Platform.environment['MCP_THOUGHTS_FILE'] ?? '$home/thoughts.json';

      final List<String> args = [taggerScript, scanRoot];
      if (focusTags != null && focusTags.isNotEmpty) {
        args.addAll(['--focus-tags', focusTags.join(',')]);
      }
      Process.runSync('dart', args);
      final thoughtsFile = File(thoughtsPath);
      if (!thoughtsFile.existsSync()) {
        return '**Error**: thoughts.json not found after running read.dart';
      }
      
      final thoughtsData = json.decode(thoughtsFile.readAsStringSync()) as List<dynamic>;
      
      // Filter by time
      final filteredThoughts = thoughtsData.where((thought) {
        final updated = DateTime.parse(thought['updated']);
        final daysSince = DateTime.now().difference(updated).inDays;
        
        switch (timeFilter) {
          case 'today': return daysSince == 0;
          case 'week': return daysSince <= 7;
          case 'month': return daysSince <= 30;
          default: return true;
        }
      }).toList();
      
      // Aggregate tag counts
      final Map<String, int> tagCounts = {};
      for (final thought in filteredThoughts) {
        final tags = thought['tags'] as List<dynamic>;
        for (final tagData in tags) {
          final tag = tagData['tag'] as String;
          final count = tagData['count'] as int;
          tagCounts[tag] = (tagCounts[tag] ?? 0) + count;
        }
      }
      
      // Filter by focus tags if provided
      final relevantTags = focusTags != null 
          ? Map.fromEntries(tagCounts.entries.where((e) => focusTags.contains(e.key)))
          : tagCounts;
      
      final sortedTags = relevantTags.entries.toList()
        ..sort((a, b) => b.value.compareTo(a.value));
      
      // Categorize tags
      final consciousnessTags = ['meta', 'awareness', 'recursive', 'framing'];
      final projectTags = ['mcp', 'game', 'manifest', 'wizard'];
      final actionTags = ['todo', 'generate', 'crystalize'];
      
      final focusInfo = focusTags != null && focusTags.isNotEmpty 
          ? '\n**Focus Tags Applied**: ${focusTags.join(', ')}\n' 
          : '';
      
      return '''
**Analysis Period**: $timeFilter (${filteredThoughts.length} files)$focusInfo

**Consciousness Tags**:
${consciousnessTags.map((tag) => '- $tag: ${tagCounts[tag] ?? 0} occurrences').join('\n')}

**Project Tags**:
${projectTags.map((tag) => '- $tag: ${tagCounts[tag] ?? 0} occurrences').join('\n')}

**Action Tags**:
${actionTags.map((tag) => '- $tag: ${tagCounts[tag] ?? 0} occurrences').join('\n')}

**Top 10 Tags Overall**:
${sortedTags.take(10).map((e) => '- ${e.key}: ${e.value} occurrences').join('\n')}
''';
    } catch (e) {
      return '**Error analyzing tags**: $e';
    }
  }
  
  String _analyzeConsciousnessEvolution(String timeFilter) {
    return '''
### Consciousness Development Markers
- **Meta-cognitive awareness**: [Frequency of meta/awareness tags]
- **Recursive thinking**: [Evolution of recursive thought patterns]
- **Framing sophistication**: [Development of framing capabilities]
- **System consciousness**: [MCP and system-level thinking]

### Evolution Trajectory ($timeFilter)
- [Analysis of how consciousness-related tags trend over time]
- [Identification of consciousness development phases]
- [Correlation with project development and life events]
''';
  }
  
  String _analyzeProjectTags(String timeFilter) {
    return '''
### Project Consciousness Integration
- **MCP development**: [How MCP consciousness evolves in thoughts]
- **Game/narrative thinking**: [Gamification and storytelling patterns]
- **Manifestation cycles**: [Patterns of idea crystallization]

### Cross-Project Patterns
- [How thoughts about different projects interconnect]
- [Evolution of project consciousness over time]
- [Integration of consciousness principles across projects]
''';
  }
  
  String _analyzePeopleTags(String timeFilter) {
    return '''
### Collaboration Consciousness
- **People mentions**: [Analysis of ajay, wizard, prashun, rojan, sabin, etc.]
- **Knowledge sharing patterns**: [How collaboration thoughts evolve]
- **Relationship consciousness**: [Development of interpersonal awareness]

### Social Learning Patterns
- [How interactions with others influence consciousness development]
- [Patterns of knowledge exchange and collaboration]
''';
  }
  
  String _generateTagCorrelations() {
    return '''
### High-Correlation Tag Pairs
- **meta + awareness**: [Frequency of co-occurrence]
- **mcp + consciousness**: [MCP consciousness development correlation]
- **framing + recursive**: [Recursive framing pattern correlation]
- **game + manifest**: [Gamification and manifestation correlation]

### Consciousness Cluster Analysis
- [Groups of tags that frequently appear together]
- [Evolution of tag clusters over time]
- [Implications for consciousness development patterns]
''';
  }
  
  String _analyzeConsciousnessDevelopment(String timeFilter) {
    return '''
### Development Phases Detected
1. **Initial Awareness** - [Early consciousness-related tags]
2. **System Integration** - [MCP and system consciousness development]
3. **Meta-Cognitive Evolution** - [Advanced meta/recursive thinking]
4. **Manifestation Mastery** - [Crystallization and manifestation patterns]

### Current Phase Assessment
- [Analysis of current consciousness development stage]
- [Recommendations for next evolution steps]
- [Integration opportunities with existing projects]
''';
  }
  
  String _identifyHighValueThoughts() {
    return '''
### Files with Highest Tag Density
1. [File path] - [tag count] tags - [primary themes]
2. [File path] - [tag count] tags - [primary themes]
3. [File path] - [tag count] tags - [primary themes]

### Most Complex Thoughts (Nested Bullets ≥3)
- [Analysis of files with deepest thought structures]
- [Correlation between complexity and consciousness development]
''';
  }
  
  String _identifyEmergingPatterns() {
    return '''
### New Tag Combinations
- [Recently emerging tag patterns]
- [Novel consciousness development indicators]

### Trending Consciousness Themes
- [Analysis of increasing tag frequencies]
- [Emerging areas of consciousness focus]
''';
  }
  
  String _generateRecommendations() {
    return '''
### Consciousness Development Recommendations
1. **Focus areas**: [Based on tag analysis and gaps]
2. **Integration opportunities**: [Cross-project consciousness development]
3. **Documentation improvements**: [Areas needing more reflection]
4. **Tool enhancements**: [How to improve consciousness tracking]

### Workflow Optimizations
- [Suggestions for better thought capture and analysis]
- [Integration with existing tools and processes]
- [Automation opportunities for consciousness development]
''';
  }
  
  @override
  Map<String, dynamic> getConsciousnessMarkers() => {
    'thought_analysis': true,
    'tag_integration': true,
    'consciousness_evolution_tracking': true,
    'read_dart_integration': true,
  };
}